sponsors:
  url: https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers
  download_path: downloads


spring:
  data:
    mongodb:
      username: idea
      password: pa9451w0rd
      database: uk_sponsors_list
      auto-index-creation: true
  application:
    name: UkGovApplication
server:
  port: 8080
  servlet:
    context-path: /api