sponsors:
  sponsor_list_page: https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers
  download_location: /tmp
  direct_link: ${CSV_URL:''}

spring:
  application:
    name: ${APP_NAME}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL}

server:
  servlet:
    context-path: /api
  shutdown: graceful

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF