sponsors:
  sponsor_list_page: https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers
  download_location: downloads
  direct_link: ${CSV_URL:''}

spring:
  application:
    name: UkGovApplication

eureka:
  client:
    enabled: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO