sponsors:
  sponsor_list_page: https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers
  download_location: ${FILE_PATH:/tmp}
  direct_link: ${CSV_URL:''}

spring:
  application:
    name: UkGovApplication

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:https://discovery.rexijie.dev/eureka/}

server:
  servlet:
    context-path: /api
  shutdown: graceful

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF