sponsors:
  sponsor_list_page: https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers
  download_location: downloads
  direct_link: ${CSV_URL:''}

spring:
  application:
    name: UkGovApplication

app:
  properties:
    cors:
      max-age: 8000
      allowedMethods: "GET"
      allowedOrigins: "http://localhost:3000,http://127.0.0.1:3000,http://192.168.1.108:3000"

eureka:
  client:
    enabled: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO